#ICICI UAT configuration
icici.VERSION = 1
icici.PASSCODE = ABCD1234
icici.BANKID = 24520
icici.TERMINALID = EG000488
icici.MERCHANTID = 100000000005859
icici.MCC = 8641
icici.TXNTYPE = Pay
icici.STATUSTYPE = Pay
icici.REFUNDTYPE = Refund
icici.REFUNDSTATUSTYPE = Refund
icici.SECURE_SECRET = 5FF1003BD85EC13EDDE106AC235F58AD
icici.ENCKEY = 1FF49170C8CCECFF1345B38F971CABBD
#icici.GATEWAYURL =  https://payuatrbac.icicibank.com/accesspoint/angularBackEnd/requestproxypass
icici.GATEWAYURL =  https://payuatrbac.icicibank.com/payment-capture/
icici.STATUS_CHECK_GATEWAY = https://payuatrbac.icicibank.com/accesspoint/v1/24520/checkStatusMerchantKit
icici.REFUND_GATEWAY = https://payuatrbac.icicibank.com/accesspoint/v1/24520/createRefundFromMerchantKit
icici.RETURNURL = http://localhost:8089/response
icici.CURRENCY = 356