#########Local DATABASE ##################

spring.datasource.url=jdbc:postgresql://10.72.4.78:5432/UDS
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




#########LIVE DATABASE ##################

#spring.datasource.url=jdbc:postgresql://10.160.6.216:5432/ecrop
#spring.datasource.username=ecrop
#spring.datasource.password=ecrop#6.216
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.show_sql=true

spring.servlet.multipart.enabled=true 
spring.servlet.multipart.maxFileSize: 2MB
spring.servlet.multipart.maxRequestSize: 2MB

spring.jpa.properties.hibernate.default_schema=uds

server.port=8085
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'
spring.mvc.format.date=yyyy-MM-dd
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict
server.servlet.session.fixation-protection=none



##Production
##SLK=LXJXX-RHRCL-FLGRA-NRJZR
#
##Preproduction licence key
#SLK=MGVBY-JAGBR-ZCCFS-STPTX
#
#
##Environment 1- production 
##Environment 0-Preproduction
#ENVIRONMENT=0
#
## UIDAI certificate(.cer file path)
#PreProdPublickey=D:/syntigen jars/uidai_auth_pre_prod.cer
##ProdPublickey=/usr/share/apache-tomcat-8.5.68/conf/uidai_auth_prod.cer


#Connection Time Out for Service Call in milliseconds (By Default : 20000 (20 Secs))
#ConnectionTimeOut=20000



## Add hikari 
spring.datasource.tomcat.initial-size=50
server.tomcat.threads.max=1000
spring.datasource.hikari.maximum-pool-size=1000
spring.datasource.hikari.minimum-idle=100
spring.datasource.tomcat.max-active=1000
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=500

spring.datasource.hikari.idle-timeout=10000 
spring.datasource.hikari.max-lifetime= 10000
server.tomcat.accept-count=100

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-post-size=10485760 

#server.servlet.session.timeout=30m

server.servlet.session.timeout=2h
