//package com.ecrops.service;
//
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.xml.bind.annotation.XmlSeeAlso;
//import javax.xml.ws.RequestWrapper;
//import javax.xml.ws.ResponseWrapper;
//
//import com.nic.ecrops.wsdl.generated.ObjectFactory;
//
//
///**
// * This class was generated by the JAX-WS RI.
// * JAX-WS RI 2.3.2
// * Generated source version: 2.2
// * 
// */
//@WebService(name = "StateWiseSearchOnUIDSoap", targetNamespace = "http://tempuri.org/")
//@XmlSeeAlso({
//    ObjectFactory.class
//})
//public interface StateWiseSearchOnUIDSoap {
//
//
//    /**
//     * 
//     * @param uid
//     * @param usrId
//     * @param pwd
//     * @param dcode
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod(operationName = "StateWiseSearchBasedonUID", action = "http://tempuri.org/StateWiseSearchBasedonUID")
//    @WebResult(name = "StateWiseSearchBasedonUIDResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "StateWiseSearchBasedonUID", targetNamespace = "http://tempuri.org/", className = "com.nic.ecrops.wsdl.generated.StateWiseSearchBasedonUID")
//    @ResponseWrapper(localName = "StateWiseSearchBasedonUIDResponse", targetNamespace = "http://tempuri.org/", className = "com.nic.ecrops.wsdl.generated.StateWiseSearchBasedonUIDResponse")
//    public String stateWiseSearchBasedonUID(
//        @WebParam(name = "UID", targetNamespace = "http://tempuri.org/")
//        String uid,
//        @WebParam(name = "Dcode", targetNamespace = "http://tempuri.org/")
//        int dcode,
//        @WebParam(name = "usr_id", targetNamespace = "http://tempuri.org/")
//        String usrId,
//        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
//        String pwd);
//
//    /**
//     * 
//     * @param usrId
//     * @param pwd
//     * @param dcode
//     * @param villageCode
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod(operationName = "StateWiseSearchBasedonVillageCode", action = "http://tempuri.org/StateWiseSearchBasedonVillageCode")
//    @WebResult(name = "StateWiseSearchBasedonVillageCodeResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "StateWiseSearchBasedonVillageCode", targetNamespace = "http://tempuri.org/", className = "com.nic.ecrops.wsdl.generated.StateWiseSearchBasedonVillageCode")
//    @ResponseWrapper(localName = "StateWiseSearchBasedonVillageCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.nic.ecrops.wsdl.generated.StateWiseSearchBasedonVillageCodeResponse")
//    public String stateWiseSearchBasedonVillageCode(
//        @WebParam(name = "VillageCode", targetNamespace = "http://tempuri.org/")
//        String villageCode,
//        @WebParam(name = "Dcode", targetNamespace = "http://tempuri.org/")
//        int dcode,
//        @WebParam(name = "usr_id", targetNamespace = "http://tempuri.org/")
//        String usrId,
//        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
//        String pwd);
//
//    /**
//     * 
//     * @param usrId
//     * @param pwd
//     * @param dcode
//     * @param villageCode
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod(operationName = "RTGSDataByVillCode", action = "http://tempuri.org/RTGSDataByVillCode")
//    @WebResult(name = "RTGSDataByVillCodeResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "RTGSDataByVillCode", targetNamespace = "http://tempuri.org/", className = "com.nic.ecrops.wsdl.generated.RTGSDataByVillCode")
//    @ResponseWrapper(localName = "RTGSDataByVillCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.nic.ecrops.wsdl.generated.RTGSDataByVillCodeResponse")
//    public String rtgsDataByVillCode(
//        @WebParam(name = "VillageCode", targetNamespace = "http://tempuri.org/")
//        String villageCode,
//        @WebParam(name = "Dcode", targetNamespace = "http://tempuri.org/")
//        int dcode,
//        @WebParam(name = "usr_id", targetNamespace = "http://tempuri.org/")
//        String usrId,
//        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
//        String pwd);
//
//}
