//package com.ecrops.controller.rest;
//
//import java.net.MalformedURLException;
//import java.net.URL;
//import javax.xml.namespace.QName;
//import javax.xml.ws.Service;
//import javax.xml.ws.WebEndpoint;
//import javax.xml.ws.WebServiceClient;
//import javax.xml.ws.WebServiceException;
//import javax.xml.ws.WebServiceFeature;
//
//import com.ecrops.service.StateWiseSearchOnUIDSoap;
//
//
///**
// * This class was generated by the JAX-WS RI.
// * JAX-WS RI 2.3.2
// * Generated source version: 2.2
// * 
// */
//@WebServiceClient(name = "StateWiseSearchOnUID", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://uatwebland.ap.gov.in/StateWiseSearchOnUID.asmx?WSDL")
//public class StateWiseSearchOnUID
//    extends Service
//{
//
//    private final static URL STATEWISESEARCHONUID_WSDL_LOCATION;
//    private final static WebServiceException STATEWISESEARCHONUID_EXCEPTION;
//    private final static QName STATEWISESEARCHONUID_QNAME = new QName("http://tempuri.org/", "StateWiseSearchOnUID");
//
//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("https://uatwebland.ap.gov.in/StateWiseSearchOnUID.asmx?WSDL");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        STATEWISESEARCHONUID_WSDL_LOCATION = url;
//        STATEWISESEARCHONUID_EXCEPTION = e;
//    }
//
//    public StateWiseSearchOnUID() {
//        super(__getWsdlLocation(), STATEWISESEARCHONUID_QNAME);
//    }
//
//    public StateWiseSearchOnUID(WebServiceFeature... features) {
//        super(__getWsdlLocation(), STATEWISESEARCHONUID_QNAME, features);
//    }
//
//    public StateWiseSearchOnUID(URL wsdlLocation) {
//        super(wsdlLocation, STATEWISESEARCHONUID_QNAME);
//    }
//
//    public StateWiseSearchOnUID(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, STATEWISESEARCHONUID_QNAME, features);
//    }
//
//    public StateWiseSearchOnUID(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public StateWiseSearchOnUID(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }
//
//    /**
//     * 
//     * @return
//     *     returns StateWiseSearchOnUIDSoap
//     */
//    @WebEndpoint(name = "StateWiseSearchOnUIDSoap")
//    public StateWiseSearchOnUIDSoap getStateWiseSearchOnUIDSoap() {
//        return super.getPort(new QName("http://tempuri.org/", "StateWiseSearchOnUIDSoap"), StateWiseSearchOnUIDSoap.class);
//    }
//
//    /**
//     * 
//     * @param features
//     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns StateWiseSearchOnUIDSoap
//     */
//    @WebEndpoint(name = "StateWiseSearchOnUIDSoap")
//    public StateWiseSearchOnUIDSoap getStateWiseSearchOnUIDSoap(WebServiceFeature... features) {
//        return super.getPort(new QName("http://tempuri.org/", "StateWiseSearchOnUIDSoap"), StateWiseSearchOnUIDSoap.class, features);
//    }
//
//    private static URL __getWsdlLocation() {
//        if (STATEWISESEARCHONUID_EXCEPTION!= null) {
//            throw STATEWISESEARCHONUID_EXCEPTION;
//        }
//        return STATEWISESEARCHONUID_WSDL_LOCATION;
//    }
//
//}
